"""image blob

Revision ID: abe5abb078d5
Revises: c79098887777
Create Date: 2016-06-03 15:57:52.696548

"""

# revision identifiers, used by Alembic.
revision = 'abe5abb078d5'
down_revision = 'c79098887777'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_image', sa.BLOB(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_image')
    ### end Alembic commands ###
